"""creating Profile, Goal, Task, and Schedule Tables

Revision ID: 4031de0351b5
Revises: 
Create Date: 2025-05-17 00:59:54.001875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4031de0351b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_pic', sa.LargeBinary(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('goal_name', sa.String(), nullable=False),
    sa.Column('goal_description', sa.String(), nullable=True),
    sa.Column('dedicated_time', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monday', sa.JSON(), nullable=True),
    sa.Column('tuesday', sa.JSON(), nullable=True),
    sa.Column('wednesday', sa.JSON(), nullable=True),
    sa.Column('thursday', sa.JSON(), nullable=True),
    sa.Column('friday', sa.JSON(), nullable=True),
    sa.Column('saturday', sa.JSON(), nullable=True),
    sa.Column('sunday', sa.JSON(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=True),
    sa.Column('days', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('dedicated_time', sa.Integer(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('schedules')
    op.drop_table('goals')
    op.drop_table('profiles')
    # ### end Alembic commands ###
